java_binary(
    name = "SpannerDemo",
    srcs = ["SpannerDemo.java"],
    deps = [
        "@maven//:com_google_cloud_google_cloud_core",
        "@maven//:com_google_cloud_google_cloud_spanner",
        "@maven//:com_google_guava_guava",
    ],
)
